services:
  frontend:
    build:
      context: ./front
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development