services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./secrets:/app/secrets:ro
    environment:
      - NODE_ENV=development
    command: npm run dev